install.packages('devtools',repos='http://cran.us.r-project.org')
require(devtools)
#The latests versions of sqldf/RSQLite were using excessive memory and causing crashes.
#I'm pinning the versions that worked correctly for me.
install_version('RSQLite', version = "1.0.0", repos='http://cran.us.r-project.org')
install_version('sqldf', version = "0.4-10", repos='http://cran.us.r-project.org')
install.packages('lsr',repos='http://cran.us.r-project.org')
install.packages('ggplot2',repos='http://cran.us.r-project.org')
install.packages('effsize',repos='http://cran.us.r-project.org')
install.packages('car',repos='http://cran.us.r-project.org')
install.packages('reshape2',repos='http://cran.us.r-project.org')
install.packages('gsubfn',repos='http://cran.us.r-project.org')
install.packages('data.table',repos='http://cran.us.r-project.org')
install.packages('coin',repos='http://cran.us.r-project.org')
install.packages('robustbase',repos='http://cran.us.r-project.org')
install.packages('plyr',repos='http://cran.us.r-project.org')
install.packages('dplyr',repos='http://cran.us.r-project.org')
install.packages('MASS',repos='http://cran.us.r-project.org')
install.packages('stargazer',repos='http://cran.us.r-project.org')
install.packages('zipfR',repos='http://cran.us.r-project.org')
install.packages('MuMIn',repos='http://cran.us.r-project.org')
install.packages('GGally',repos='http://cran.us.r-project.org')
install.packages('stargazer',repos='http://cran.us.r-project.org')
install.packages('grid', repos='http://cran.us.r-project.org')
install.packages('gridExtra', repos='http://cran.us.r-project.org')
