mkdir -p NgramCacheModel/evaluation/data/lstm_comparable
mkdir -p ptb

mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/clojure/no_collapse_names
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/eng_parse_manual/full_type
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/german/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/commits/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/djava/no_collapse_small
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/spanish/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/haskell/no_collapse_names
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/ruby/no_collapse
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/eng/names
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/scifi/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/shakespeare/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/brown/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/ruby/no_collapse_names
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/djava/ast
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/djava/text
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/brown/names
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/haskell/no_collapse
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/c/no_collapse
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/teccl/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/law/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/djava/no_collapse_names
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/clojure/no_collapse
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/eng_parse_manual/simp_post
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/eng_parse_manual/text
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/recipes/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/nasa/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/c/no_collapse_names
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/eng/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/gachon/full
mkdir -p NgramCacheModel/evaluation/data/lstm_comparable/djava/no_collapse

mkdir -p ptb/clojure_no_collapse_names
mkdir -p ptb/eng_parse_manual_full_type
mkdir -p ptb/german
mkdir -p ptb/commits
mkdir -p ptb/djava_no_collapse_small
mkdir -p ptb/spanish
mkdir -p ptb/haskell_no_collapse_names
mkdir -p ptb/ruby_no_collapse
mkdir -p ptb/eng_names
mkdir -p ptb/scifi
mkdir -p ptb/shakespeare
mkdir -p ptb/brown_data
mkdir -p ptb/ruby_no_collapse_names
mkdir -p ptb/djava_ast
mkdir -p ptb/djava_ast_text
mkdir -p ptb/brown_names
mkdir -p ptb/haskell_no_collapse
mkdir -p ptb/c_no_collapse
mkdir -p ptb/teccl
mkdir -p ptb/law
mkdir -p ptb/djava_no_collapse_names
mkdir -p ptb/clojure_no_collapse
mkdir -p ptb/eng_parse_manual
mkdir -p ptb/eng_parse_manual_text
mkdir -p ptb/recipes
mkdir -p ptb/nasa
mkdir -p ptb/c_no_collapse_names
mkdir -p ptb/eng_data
mkdir -p ptb/gachon
mkdir -p ptb/djava_no_collapse
